In [1]:
from ase.collections import g2

import json
import numpy as np

from pyscf.data.elements import ELEMENTS

dict_ = {"molecular": [], "spin": {}, "charge": {}, "reaction-atomic-energy": {}}
name = g2.names

for i_name in name:
    positions = np.array(g2[i_name].get_positions())
    numbers = g2[i_name].numbers

    print(numbers)

    molecular = []
    total_ele = 0
    for i_number, atom_number in enumerate(numbers):
        atom = []
        total_ele += atom_number
        atom.append(ELEMENTS[atom_number])
        atom.append(float(positions[i_number][0]))
        atom.append(float(positions[i_number][1]))
        atom.append(float(positions[i_number][2]))
        molecular.append(atom)

    dict_[i_name] = molecular
    dict_["molecular"].append(i_name)
    dict_["spin"][i_name] = int(sum(g2[i_name].get_initial_magnetic_moments()))
    dict_["charge"][i_name] = int(sum(g2[i_name].get_initial_charges()))

    systems_list = [i_name]
    stoichiometry_list = ["-1"]
    for atom_number in numbers:
        systems_list.append(ELEMENTS[atom_number])
        stoichiometry_list.append("1")

    dict_["reaction-atomic-energy"][i_name] = {
        "systems": systems_list,
        "stoichiometry": stoichiometry_list,
    }

[15  1  1  1]
[15 15]
[8 6 1 6 1 1 1]
[6 8 1 1 1]
[ 6 16]
[6 6 8 1 8 1]
[6 6 6 6 1 1 1 1 1 1 1 1 1]
[6 8 9 6 1 1 1]
[8 6 6 6 1 1 1 1 1 1 1 1]
[8 6 8 1 1]
[ 6  1 17 17 17]
[ 8  1 17]
[1 1]
[16  1  1]
[6 6 1 1]
[1 7 6 6 6 6 1 1 1 1]
[ 6 16  6  1  1  1  1  1  1]
[14  1  1]
[ 6 16  1  1  1  1]
[6 6 1 1 1 8]
[8 6]
[17  9  9  9]
[14  1  1  1  1]
[8 6 1 1 6 6 1 1 1 1 1 1]
[6 7 6 1 1 1 1 1]
[6 6 1 1 6 1 1 1 6 1 1 1]
[6 8 1]
[6 6 6 6 1 1 1 1 1 1]
[3 9]
[14]
[6 6 1 1 1 1 1 1]
[6 7]
[17  7  8]
[16]
[14  9  9  9  9]
[6 7 1 1 1 1 1]
[6 6 6 6 1 1 1 1 1 1]
[6 6 8 1 1 1 1 1 1]
[9]
[11 17]
[ 6 17  1  1  1]
[ 6 14  1  1  1  1  1  1]
[13  9  9  9]
[6 6 1 1 1]
[ 9 17]
[15  9  9  9]
[15  1  1]
[6 6 7 1 1 1]
[6 6 6 6 1 1 1 1 1 1]
[6 8 1 1 1 7 8]
[14  1  1  1]
[6 6 6 1 1 1 1 1 1]
[6 8 8]
[7 8]
[6 6 6 6 1 1 1 1 1 1 1 1 1 1]
[ 6  6 17  1  1  1]
[3 1]
[7 1 1]
[6 1]
[6 8 6 1 1 1 1]
[6 6 6 6 6 6 1 1 1 1 1 1]
[8 6 7 6 1 1 1 1 1]
[6 6 6 6 1 1 1 1 1 1 1 1]
[6 6 6 1 1 1 7]
[6 6 6 6 1 1 1 1 1 1]
[6]
[8 6 1 1]
[6 8 8 1

In [3]:
with open("../cadft/utils/g2.json", "w") as f:
    json.dump(dict_, f)