In [1]:
from torchinfo import summary
import segmentation_models_pytorch as smp

import torch
import torch.nn as nn

from cadft.utils.model.transformer import PredictorSmall

device = torch.device("cpu")
model = PredictorSmall()

# inputs size is (10, 75, 302, 1)
inputs = torch.randn(1, 1, 40, 194)
inputs = inputs.to(device)
print(inputs.shape, model(inputs).shape)

print(
    summary(
        model,
        input_size=(1, 1, 40, 194),
        device="cpu",
        col_names=("input_size", "output_size", "num_params"),
        col_width=16,
    )
)

MAIN_PATH: /home/dhem/workspace/2024.1
DATA_PATH: /home/dhem/workspace/2024.1/data/grids_mrks
DATA_SAVE_PATH: /home/dhem/workspace/2024.1/data/grids_mrks/saved_data
DATA_CC_PATH: /home/dhem/workspace/2024.1/data/test
torch.Size([1, 1, 40, 194]) torch.Size([1, 1, 40, 194])
Layer (type:depth-idx)                   Input Shape      Output Shape     Param #
PredictorSmall                           [1, 1, 40, 194]  [1, 1, 40, 194]  --
├─Extractor: 1-1                         [1, 1, 40, 194]  [1, 1, 40, 194]  --
│    └─Linear: 2-1                       [1, 194, 40]     [1, 194, 256]    10,496
│    └─GELU: 2-2                         [1, 194, 256]    [1, 194, 256]    --
│    └─ModuleList: 2-3                   --               --               --
│    │    └─ABlock: 3-1                  [1, 194, 256]    [1, 194, 256]    788,736
│    │    └─ABlock: 3-2                  [1, 194, 256]    [1, 194, 256]    788,736
│    │    └─ABlock: 3-3                  [1, 194, 256]    [1, 194, 256]    788,736
│

In [2]:
inputs = inputs.to(device)
model(inputs)[0]

tensor([[[-0.0151, -0.1119,  0.0313,  ...,  0.1267,  0.0323,  0.2091],
         [-0.1445, -0.0880, -0.0952,  ...,  0.2460, -0.0891, -0.1801],
         [-0.1600,  0.0046,  0.0784,  ..., -0.0506,  0.3938,  0.1699],
         ...,
         [-0.1557, -0.0524, -0.1232,  ...,  0.0133, -0.4861, -0.0218],
         [-0.0077, -0.0585,  0.0266,  ...,  0.0890, -0.0807,  0.1009],
         [-0.0276,  0.2495, -0.1343,  ...,  0.0889, -0.0890, -0.0558]]],
       grad_fn=<SelectBackward0>)

In [3]:
inputs[:, :, [0, 1], :] = inputs[:, :, [1, 0], :]
inputs = inputs.to(device)
model(inputs)[0]

tensor([[[-0.0108, -0.1116,  0.0331,  ...,  0.1172,  0.0207,  0.2071],
         [-0.1602, -0.0836, -0.0991,  ...,  0.2563, -0.0802, -0.1661],
         [-0.1564,  0.0041,  0.0817,  ..., -0.0447,  0.3881,  0.1793],
         ...,
         [-0.1603, -0.0541, -0.1255,  ...,  0.0121, -0.4803, -0.0191],
         [-0.0170, -0.0600,  0.0273,  ...,  0.0930, -0.0631,  0.0884],
         [-0.0393,  0.2549, -0.1361,  ...,  0.0866, -0.0728, -0.0398]]],
       grad_fn=<SelectBackward0>)

In [4]:
inputs[:, :, :, [0, 1]] = inputs[:, :, :, [1, 0]]
inputs = inputs.to(device)
model(inputs)[0]

tensor([[[-0.1116, -0.0108,  0.0331,  ...,  0.1172,  0.0207,  0.2071],
         [-0.0836, -0.1602, -0.0991,  ...,  0.2563, -0.0802, -0.1661],
         [ 0.0041, -0.1564,  0.0817,  ..., -0.0447,  0.3881,  0.1793],
         ...,
         [-0.0541, -0.1603, -0.1255,  ...,  0.0121, -0.4803, -0.0191],
         [-0.0600, -0.0170,  0.0273,  ...,  0.0930, -0.0631,  0.0884],
         [ 0.2549, -0.0393, -0.1361,  ...,  0.0866, -0.0728, -0.0398]]],
       grad_fn=<SelectBackward0>)

In [10]:
model(inputs)[0, 0, :, 0], model(inputs)[0, 0, :, 1]

(tensor([-0.1116, -0.0836,  0.0041,  0.2695, -0.0109,  0.0074,  0.0445, -0.0276,
         -0.1394, -0.0176,  0.0387,  0.2052, -0.0754, -0.1276, -0.0498, -0.0356,
         -0.0111,  0.1684,  0.1977,  0.0540, -0.0192,  0.1271,  0.2687, -0.0018,
          0.0914,  0.0336,  0.2151,  0.2706,  0.0489,  0.0355,  0.0166,  0.0887,
          0.0437, -0.0285, -0.0356, -0.0324,  0.1377, -0.0541, -0.0600,  0.2549],
        grad_fn=<SelectBackward0>),
 tensor([-0.0108, -0.1602, -0.1564,  0.1157,  0.0351,  0.2234,  0.0738,  0.0739,
         -0.2800,  0.0381, -0.0485, -0.0188,  0.0234, -0.2624,  0.1170, -0.1075,
         -0.1922, -0.1333, -0.1049,  0.2508, -0.0188, -0.1018,  0.1882,  0.0363,
          0.1111,  0.1406,  0.0929,  0.0204,  0.0034,  0.0077,  0.1094,  0.1266,
          0.0051, -0.0537, -0.0211, -0.1649,  0.2429, -0.1603, -0.0170, -0.0393],
        grad_fn=<SelectBackward0>))