In [1]:
from pyscf.geomopt.geometric_solver import optimize
from pyscf import gto, scf

MOL = """   
    0.6558    0.3935    0.0001 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6558   -0.3932    0.0227 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.8649   -0.5413   -0.0114 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.8650    0.5414    0.0001 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.1709    0.2369   -0.0001 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.1709   -0.2372   -0.0115 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.6840    1.0388   -0.8865 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.7045    1.0489    0.8783 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6930   -1.0225    0.9203 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6952   -1.0642   -0.8441 H   0  0  0  0  0  0  0  0  0  0  0  0
    1.8337   -1.2015    0.8633 H   0  0  0  0  0  0  0  0  0  0  0  0
    1.8334   -1.1803   -0.9015 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.8442    1.1983    0.8775 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.8234    1.1837   -0.8874 H   0  0  0  0  0  0  0  0  0  0  0  0
    3.2485    0.8856   -0.8784 H   0  0  0  0  0  0  0  0  0  0  0  0
    4.0222   -0.4510   -0.0096 H   0  0  0  0  0  0  0  0  0  0  0  0
    3.2483    0.8607    0.8961 H   0  0  0  0  0  0  0  0  0  0  0  0
   -3.2373   -0.8791   -0.8958 H   0  0  0  0  0  0  0  0  0  0  0  0
   -3.2592   -0.8681    0.8788 H   0  0  0  0  0  0  0  0  0  0  0  0
   -4.0221    0.4505   -0.0263 H   0  0  0  0  0  0  0  0  0  0  0  0
"""
molecular = []
for line in MOL.split("\n"):
    line_split = line.split()
    atom = []
    if len(line_split):
        atom.append(line_split[3])
        atom.append(float(line_split[0]))
        atom.append(float(line_split[1]))
        atom.append(float(line_split[2]))
        molecular.append(atom)
print(molecular)

mol = gto.M(atom=molecular, basis="ccpvdz")
mdft = mol.KS()
mdft.xc = "b3lyp"
mdft.kernel()
mol_eq = optimize(mdft, maxsteps=100)
print(mol_eq.atom_coords())

/home/dhem/anaconda3/envs/pyscf/lib/python3.11/site-packages/pyscf/dft/libxc.py:771: UserWarning: Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, corresponding to the original definition by Stephens et al. (issue 1480) and the same as the B3LYP functional in Gaussian. To restore the VWN5 definition, you can put the setting "B3LYP_WITH_VWN5 = True" in pyscf_conf.py
  warnings.warn('Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, '


[['C', 0.6558, 0.3935, 0.0001], ['C', -0.6558, -0.3932, 0.0227], ['C', 1.8649, -0.5413, -0.0114], ['C', -1.865, 0.5414, 0.0001], ['C', 3.1709, 0.2369, -0.0001], ['C', -3.1709, -0.2372, -0.0115], ['H', 0.684, 1.0388, -0.8865], ['H', 0.7045, 1.0489, 0.8783], ['H', -0.693, -1.0225, 0.9203], ['H', -0.6952, -1.0642, -0.8441], ['H', 1.8337, -1.2015, 0.8633], ['H', 1.8334, -1.1803, -0.9015], ['H', -1.8442, 1.1983, 0.8775], ['H', -1.8234, 1.1837, -0.8874], ['H', 3.2485, 0.8856, -0.8784], ['H', 4.0222, -0.451, -0.0096], ['H', 3.2483, 0.8607, 0.8961], ['H', -3.2373, -0.8791, -0.8958], ['H', -3.2592, -0.8681, 0.8788], ['H', -4.0221, 0.4505, -0.0263]]
converged SCF energy = -237.085665917627


geometric-optimize called with the following command line:
/home/dhem/anaconda3/envs/pyscf/lib/python3.11/site-packages/ipykernel_launcher.py --f=/home/dhem/.local/share/jupyter/runtime/kernel-v2-555131NuxluMT7yq8f.json

                                        ())))))))))))))))/                     
                                    ())))))))))))))))))))))))),                
                                *)))))))))))))))))))))))))))))))))             
                        #,    ()))))))))/                .)))))))))),          
                      #%%%%,  ())))))                        .))))))))*        
                      *%%%%%%,  ))              ..              ,))))))).      
                        *%%%%%%,         ***************/.        .)))))))     
                #%%/      (%%%%%%,    /*********************.       )))))))    
              .%%%%%%#      *%%%%%%,  *******/,     **********,      .))))))   
                .%%%%%%/      *%%%%%%,  **              ***


Geometry optimization cycle 1
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C   0.655800   0.393500   0.000100    0.000000  0.000000  0.000000
   C  -0.655800  -0.393200   0.022700    0.000000  0.000000  0.000000
   C   1.864900  -0.541300  -0.011400   -0.000000  0.000000  0.000000
   C  -1.865000   0.541400   0.000100    0.000000  0.000000  0.000000
   C   3.170900   0.236900  -0.000100    0.000000 -0.000000  0.000000
   C  -3.170900  -0.237200  -0.011500    0.000000  0.000000  0.000000
   H   0.684000   1.038800  -0.886500    0.000000  0.000000  0.000000
   H   0.704500   1.048900   0.878300    0.000000  0.000000 -0.000000
   H  -0.693000  -1.022500   0.920300    0.000000  0.000000  0.000000
   H  -0.695200  -1.064200  -0.844100    0.000000  0.000000  0.000000
   H   1.833700  -1.201500   0.863300    0.000000  0.000000  0.000000
   H   1.833400  -1.180300  -0.901500    0.000000  0.000000  0.000000
   H  -1.844200   1.198300   0.8

Step    0 : Gradient = 8.576e-03/1.778e-02 (rms/max) Energy = -237.0856659176
Hessian Eigenvalues: 2.30000e-02 2.30000e-02 2.30000e-02 ... 3.42815e-01 3.42937e-01 3.43101e-01



Geometry optimization cycle 2
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C   0.669685   0.379278  -0.000754    0.013885 -0.014222 -0.000854
   C  -0.669652  -0.378764   0.016767   -0.013852  0.014436 -0.005933
   C   1.907008  -0.533259  -0.008768    0.042108  0.008041  0.002632
   C  -1.907177   0.533348  -0.001725   -0.042177 -0.008052 -0.001825
   C   3.238381   0.234490   0.000947    0.067481 -0.002410  0.001047
   C  -3.238288  -0.234926  -0.008970   -0.067388  0.002274  0.002530
   H   0.701095   1.034678  -0.890234    0.017095 -0.004122 -0.003734
   H   0.719956   1.044038   0.880970    0.015456 -0.004862  0.002670
   H  -0.709282  -1.019194   0.916677   -0.016282  0.003306 -0.003623
   H  -0.711498  -1.058168  -0.854249   -0.016298  0.006032 -0.010149
   H   1.864940  -1.203234   0.868982    0.031240 -0.001734  0.005682
   H   1.866714  -1.183947  -0.900838    0.033314 -0.003647  0.000662
   H  -1.875032   1.200146   0.8

Step    1 : Displace = 5.343e-02/8.390e-02 (rms/max) Trust = 1.000e-01 (=) Grad = 1.627e-03/2.924e-03 (rms/max) E (change) = -237.0876783723 (-2.012e-03) Quality = 0.818
Hessian Eigenvalues: 2.29637e-02 2.30000e-02 2.30000e-02 ... 3.42806e-01 3.43022e-01 3.66701e-01



Geometry optimization cycle 3
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C   0.666034   0.380171  -0.001047   -0.003651  0.000893 -0.000293
   C  -0.666001  -0.379686   0.014703    0.003652 -0.000922 -0.002064
   C   1.897209  -0.534304  -0.007764   -0.009799 -0.001045  0.001005
   C  -1.897370   0.534390  -0.002172    0.009807  0.001042 -0.000447
   C   3.222490   0.234565   0.001212   -0.015891  0.000075  0.000265
   C  -3.222390  -0.234971  -0.008062    0.015897 -0.000045  0.000908
   H   0.698435   1.039598  -0.889153   -0.002660  0.004921  0.001081
   H   0.714988   1.048375   0.879747   -0.004968  0.004336 -0.001222
   H  -0.705763  -1.025614   0.912334    0.003518 -0.006420 -0.004344
   H  -0.707407  -1.061139  -0.856323    0.004091 -0.002971 -0.002074
   H   1.855021  -1.206129   0.869583   -0.009919 -0.002895  0.000602
   H   1.857361  -1.189101  -0.897941   -0.009353 -0.005154  0.002897
   H  -1.864263   1.203810   0.8

Step    2 : Displace = 1.242e-02/1.842e-02 (rms/max) Trust = 1.414e-01 (+) Grad = 7.182e-04/1.432e-03 (rms/max) E (change) = -237.0878521656 (-1.738e-04) Quality = 1.166
Hessian Eigenvalues: 2.24999e-02 2.30000e-02 2.30000e-02 ... 3.42804e-01 3.43018e-01 3.44539e-01



Geometry optimization cycle 4
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C   0.665501   0.379486  -0.001334   -0.000533 -0.000684 -0.000286
   C  -0.665470  -0.379093   0.012248    0.000531  0.000593 -0.002456
   C   1.896158  -0.533707  -0.006523   -0.001050  0.000597  0.001241
   C  -1.896287   0.533776  -0.002650    0.001083 -0.000614 -0.000478
   C   3.220171   0.233836   0.001454   -0.002319 -0.000728  0.000243
   C  -3.220091  -0.234161  -0.006946    0.002300  0.000809  0.001115
   H   0.699753   1.041348  -0.887738    0.001317  0.001750  0.001414
   H   0.713452   1.049475   0.878324   -0.001535  0.001100 -0.001424
   H  -0.705954  -1.029351   0.906922   -0.000190 -0.003737 -0.005412
   H  -0.707039  -1.060511  -0.858937    0.000368  0.000627 -0.002614
   H   1.853810  -1.205817   0.870589   -0.001210  0.000312  0.001006
   H   1.856495  -1.191546  -0.894491   -0.000866 -0.002445  0.003450
   H  -1.861835   1.204491   0.8

Step    3 : Displace = 2.952e-03/6.612e-03 (rms/max) Trust = 2.000e-01 (+) Grad = 1.749e-04/3.843e-04 (rms/max) E (change) = -237.0878697322 (-1.757e-05) Quality = 1.266
Hessian Eigenvalues: 1.74269e-02 2.30000e-02 2.30000e-02 ... 3.42812e-01 3.43024e-01 3.70249e-01



Geometry optimization cycle 5
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C   0.665538   0.379001  -0.001527    0.000038 -0.000485 -0.000194
   C  -0.665517  -0.378719   0.009875   -0.000047  0.000374 -0.002373
   C   1.896357  -0.533600  -0.005248    0.000198  0.000107  0.001275
   C  -1.896446   0.533645  -0.003043   -0.000159 -0.000131 -0.000393
   C   3.220450   0.233390   0.001591    0.000279 -0.000446  0.000136
   C  -3.220394  -0.233621  -0.005862   -0.000304  0.000541  0.001084
   H   0.701318   1.042056  -0.887060    0.001565  0.000707  0.000679
   H   0.712376   1.049548   0.877845   -0.001077  0.000073 -0.000479
   H  -0.706450  -1.032115   0.902323   -0.000496 -0.002764 -0.004599
   H  -0.707096  -1.058805  -0.862424   -0.000056  0.001707 -0.003487
   H   1.853782  -1.205049   0.872432   -0.000028  0.000768  0.001843
   H   1.856554  -1.193592  -0.891683    0.000059 -0.002046  0.002808
   H  -1.860556   1.204762   0.8

Step    4 : Displace = 2.210e-03/5.415e-03 (rms/max) Trust = 2.828e-01 (+) Grad = 7.156e-05/1.193e-04 (rms/max) E (change) = -237.0878731464 (-3.414e-06) Quality = 1.430
Hessian Eigenvalues: 8.18825e-03 2.30000e-02 2.30000e-02 ... 3.42830e-01 3.43024e-01 3.62351e-01



Geometry optimization cycle 6
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C   0.665654   0.378654  -0.001706    0.000115 -0.000347 -0.000179
   C  -0.665644  -0.378503   0.006880   -0.000127  0.000216 -0.002995
   C   1.896525  -0.533803  -0.003575    0.000168 -0.000204  0.001673
   C  -1.896569   0.533820  -0.003461   -0.000123  0.000176 -0.000418
   C   3.220863   0.232803   0.001672    0.000413 -0.000587  0.000082
   C  -3.220837  -0.232925  -0.004515   -0.000442  0.000696  0.001347
   H   0.703276   1.042475  -0.886609    0.001958  0.000419  0.000450
   H   0.710986   1.049134   0.877815   -0.001390 -0.000414 -0.000030
   H  -0.707043  -1.035229   0.896883   -0.000593 -0.003115 -0.005440
   H  -0.707148  -1.056011  -0.867442   -0.000052  0.002793 -0.005018
   H   1.853863  -1.203674   0.875332    0.000080  0.001375  0.002899
   H   1.856603  -1.195967  -0.888410    0.000049 -0.002375  0.003273
   H  -1.859019   1.204768   0.8

Step    5 : Displace = 2.787e-03/6.336e-03 (rms/max) Trust = 3.000e-01 (+) Grad = 1.366e-04/2.855e-04 (rms/max) E (change) = -237.0878752838 (-2.137e-06) Quality = 1.559
Hessian Eigenvalues: 3.46134e-03 2.30000e-02 2.30000e-02 ... 3.42813e-01 3.43022e-01 3.58285e-01



Geometry optimization cycle 7
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C   0.665853   0.378293  -0.001930    0.000200 -0.000361 -0.000224
   C  -0.665860  -0.378305   0.001870   -0.000216  0.000198 -0.005010
   C   1.896513  -0.534498  -0.000697   -0.000011 -0.000694  0.002879
   C  -1.896508   0.534481  -0.004057    0.000062  0.000661 -0.000596
   C   3.221244   0.231670   0.001687    0.000381 -0.001133  0.000014
   C  -3.221252  -0.231663  -0.002309   -0.000415  0.001262  0.002206
   H   0.706531   1.042868  -0.886135    0.003256  0.000393  0.000474
   H   0.708619   1.048081   0.878244   -0.002367 -0.001053  0.000429
   H  -0.707986  -1.040164   0.888037   -0.000943 -0.004935 -0.008846
   H  -0.707189  -1.050794  -0.876315   -0.000042  0.005217 -0.008873
   H   1.853762  -1.201129   0.880665   -0.000101  0.002545  0.005333
   H   1.856304  -1.199936  -0.883064   -0.000299 -0.003969  0.005346
   H  -1.856227   1.204573   0.8

Step    6 : Displace = 4.706e-03/1.025e-02 (rms/max) Trust = 3.000e-01 (=) Grad = 1.375e-04/3.100e-04 (rms/max) E (change) = -237.0878774578 (-2.174e-06) Quality = 1.245
Hessian Eigenvalues: 2.67845e-03 2.30000e-02 2.30000e-02 ... 3.42811e-01 3.43024e-01 3.64645e-01



Geometry optimization cycle 8
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C   0.665961   0.378217  -0.001958    0.000108 -0.000077 -0.000027
   C  -0.665969  -0.378259  -0.000687   -0.000109  0.000046 -0.002557
   C   1.896268  -0.535175   0.000868   -0.000246 -0.000677  0.001565
   C  -1.896258   0.535155  -0.004234    0.000250  0.000674 -0.000178
   C   3.221216   0.230797   0.001542   -0.000027 -0.000873 -0.000145
   C  -3.221229  -0.230770  -0.001253    0.000022  0.000893  0.001057
   H   0.708234   1.042866  -0.886004    0.001702 -0.000001  0.000130
   H   0.707399   1.047270   0.878805   -0.001220 -0.000811  0.000561
   H  -0.708458  -1.042518   0.883641   -0.000473 -0.002354 -0.004396
   H  -0.707207  -1.047698  -0.881166   -0.000018  0.003096 -0.004851
   H   1.853494  -1.199725   0.883770   -0.000268  0.001403  0.003105
   H   1.855764  -1.202132  -0.880317   -0.000539 -0.002196  0.002747
   H  -1.854586   1.204371   0.8

Step    7 : Displace = 2.504e-03/5.638e-03 (rms/max) Trust = 3.000e-01 (=) Grad = 6.064e-05/1.421e-04 (rms/max) E (change) = -237.0878780416 (-5.838e-07) Quality = 0.897
Hessian Eigenvalues: 2.86048e-03 2.26751e-02 2.30000e-02 ... 3.42811e-01 3.43022e-01 3.61410e-01



Geometry optimization cycle 9
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C   0.666006   0.378224  -0.001865    0.000045  0.000007  0.000093
   C  -0.666010  -0.378242  -0.000979   -0.000042  0.000016 -0.000292
   C   1.896074  -0.535569   0.001154   -0.000193 -0.000394  0.000286
   C  -1.896074   0.535557  -0.004106    0.000183  0.000402  0.000129
   C   3.221100   0.230297   0.001345   -0.000116 -0.000500 -0.000197
   C  -3.221107  -0.230290  -0.001216    0.000122  0.000480  0.000037
   H   0.708556   1.042727  -0.885990    0.000322 -0.000139  0.000014
   H   0.707320   1.046953   0.879129   -0.000079 -0.000317  0.000324
   H  -0.708587  -1.042720   0.883164   -0.000128 -0.000202 -0.000477
   H  -0.707300  -1.046995  -0.881956   -0.000093  0.000704 -0.000790
   H   1.853307  -1.199565   0.884454   -0.000187  0.000160  0.000684
   H   1.855346  -1.202692  -0.879879   -0.000418 -0.000560  0.000438
   H  -1.854209   1.204316   0.8

Step    8 : Displace = 4.907e-04/9.832e-04 (rms/max) Trust = 3.000e-01 (=) Grad = 9.986e-06/2.009e-05 (rms/max) E (change) = -237.0878780386 (+2.993e-09) Quality = -0.025
Hessian Eigenvalues: 2.86048e-03 2.26751e-02 2.30000e-02 ... 3.42811e-01 3.43022e-01 3.61410e-01
Converged! =D

    #==========================================================================#
    #| If this code has benefited your research, please support us by citing: |#
    #|                                                                        |#
    #| Wang, L.-P.; Song, C.C. (2016) "Geometry optimization made simple with |#
    #| translation and rotation coordinates", J. Chem, Phys. 144, 214108.     |#
    #| http://dx.doi.org/10.1063/1.4952956                                    |#
    #==========================================================================#
    Time elapsed since start of run_optimizer: 201.873 seconds


[[ 1.25856961e+00  7.14739339e-01 -3.52361419e-03]
 [-1.25857656e+00 -7.14774495e-01 -1.84933179e-03]
 [ 3.58306146e+00 -1.01207895e+00  2.18100642e-03]
 [-3.58306101e+00  1.01205546e+00 -7.75835546e-03]
 [ 6.08699658e+00  4.35197792e-01  2.54138150e-03]
 [-6.08701032e+00 -4.35185663e-01 -2.29698874e-03]
 [ 1.33897632e+00  1.97046847e+00 -1.67427879e+00]
 [ 1.33664053e+00  1.97845537e+00  1.66131247e+00]
 [-1.33903444e+00 -1.97045603e+00  1.66893810e+00]
 [-1.33660343e+00 -1.97853355e+00 -1.66665504e+00]
 [ 3.50224302e+00 -2.26684993e+00  1.67137493e+00]
 [ 3.50609582e+00 -2.27275907e+00 -1.66272973e+00]
 [-3.50394739e+00  2.27582811e+00  1.65470860e+00]
 [-3.50436927e+00  2.26372047e+00 -1.67938067e+00]
 [ 6.25385876e+00  1.65845396e+00 -1.67815665e+00]
 [ 7.71964855e+00 -8.57713005e-01  4.40309559e-03]
 [ 6.25196800e+00  1.66094081e+00  1.68160456e+00]
 [-6.25375524e+00 -1.66465524e+00 -1.67846204e+00]
 [-6.25212409e+00 -1.65470244e+00  1.68128482e+00]
 [-7.71964841e+00  8.57740004e-

In [2]:
import numpy as np
import copy

molecular_new = copy.deepcopy(molecular)
for i, atom in enumerate(molecular_new):
    atom[1] = mol_eq.atom_coords(unit="ANG")[i][0]
    atom[2] = mol_eq.atom_coords(unit="ANG")[i][1]
    atom[3] = mol_eq.atom_coords(unit="ANG")[i][2]
# molecular
%precision 3
molecular_new

[['C', 0.666, 0.378, -0.002],
 ['C', -0.666, -0.378, -0.001],
 ['C', 1.896, -0.536, 0.001],
 ['C', -1.896, 0.536, -0.004],
 ['C', 3.221, 0.230, 0.001],
 ['C', -3.221, -0.230, -0.001],
 ['H', 0.709, 1.043, -0.886],
 ['H', 0.707, 1.047, 0.879],
 ['H', -0.709, -1.043, 0.883],
 ['H', -0.707, -1.047, -0.882],
 ['H', 1.853, -1.200, 0.884],
 ['H', 1.855, -1.203, -0.880],
 ['H', -1.854, 1.204, 0.876],
 ['H', -1.854, 1.198, -0.889],
 ['H', 3.309, 0.878, -0.888],
 ['H', 4.085, -0.454, 0.002],
 ['H', 3.308, 0.879, 0.890],
 ['H', -3.309, -0.881, -0.888],
 ['H', -3.308, -0.876, 0.890],
 ['H', -4.085, 0.454, -0.003]]

In [5]:
a = np.array([-4])
np.sqrt(np.abs(a)) * np.sign(a)

array([-2.])

In [8]:
import copy
from pyscf import gto, scf

molecular = [
["C", 0.00000000e+00, 0.00000000e+00 ,0.00000000e+00],
["H", 2.96704474e-16, -2.32926728e-32, 2.06330453e+00],
["H", 1.94530216e+00, 0.00000000e+00 ,-6.87768176e-01],
["H" ,-9.72651082e-01, 1.68468109e+00 ,-6.87768176e-01],
["H" ,-9.72651082e-01, -1.68468109e+00, -6.87768176e-01],
]

mol = gto.M(atom=molecular, basis="ccpvdz", unit="bohr")

molecular_new = copy.deepcopy(molecular)
for i, atom in enumerate(molecular_new):
    atom[1] = mol.atom_coords(unit="ANG")[i][0]
    atom[2] = mol.atom_coords(unit="ANG")[i][1]
    atom[3] = mol.atom_coords(unit="ANG")[i][2]
# print(mol.atom_coords(unit="ANG"))
%precision 3
molecular_new

[['C', 0.000, 0.000, 0.000],
 ['H', 0.000, -0.000, 1.092],
 ['H', 1.029, 0.000, -0.364],
 ['H', -0.515, 0.891, -0.364],
 ['H', -0.515, -0.891, -0.364]]