In [11]:
from pyscf.geomopt.geometric_solver import optimize
from pyscf import gto, scf

MOL = """
   -0.5630    0.5160    0.0071 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.5630   -0.5159    0.0071 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.9293   -0.1506   -0.0071 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.9294    0.1505   -0.0071 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4724    1.1666   -0.8706 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4825    1.1551    0.8940 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.4825   -1.1551    0.8940 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.4723   -1.1665   -0.8706 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.0542   -0.7710   -0.9003 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.0651   -0.7856    0.8742 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.7203    0.6060   -0.0058 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.0542    0.7709   -0.9003 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.7202   -0.6062   -0.0059 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.0652    0.7854    0.8743 H   0  0  0  0  0  0  0  0  0  0  0  0
"""
molecular = []
for line in MOL.split("\n"):
    line_split = line.split()
    atom = []
    if len(line_split):
        atom.append(line_split[3])
        atom.append(float(line_split[0]))
        atom.append(float(line_split[1]))
        atom.append(float(line_split[2]))
        molecular.append(atom)
print(molecular)

mol = gto.M(atom=molecular, basis="ccpvdz")
mdft = mol.KS()
mdft.xc = "b3lyp"
mdft.kernel()
mol_eq = optimize(mdft, maxsteps=100)
print(mol_eq.atom_coords())

[['C', -0.563, 0.516, 0.0071], ['C', 0.563, -0.5159, 0.0071], ['C', -1.9293, -0.1506, -0.0071], ['C', 1.9294, 0.1505, -0.0071], ['H', -0.4724, 1.1666, -0.8706], ['H', -0.4825, 1.1551, 0.894], ['H', 0.4825, -1.1551, 0.894], ['H', 0.4723, -1.1665, -0.8706], ['H', -2.0542, -0.771, -0.9003], ['H', -2.0651, -0.7856, 0.8742], ['H', -2.7203, 0.606, -0.0058], ['H', 2.0542, 0.7709, -0.9003], ['H', 2.7202, -0.6062, -0.0059], ['H', 2.0652, 0.7854, 0.8743]]
converged SCF energy = -158.457415637773


geometric-optimize called with the following command line:
/home/dhem/anaconda3/envs/pyscf/lib/python3.11/site-packages/ipykernel_launcher.py --f=/home/dhem/.local/share/jupyter/runtime/kernel-v2-446562eGEyMzb6X8iA.json

                                        ())))))))))))))))/                     
                                    ())))))))))))))))))))))))),                
                                *)))))))))))))))))))))))))))))))))             
                        #,    ()))))))))/                .)))))))))),          
                      #%%%%,  ())))))                        .))))))))*        
                      *%%%%%%,  ))              ..              ,))))))).      
                        *%%%%%%,         ***************/.        .)))))))     
                #%%/      (%%%%%%,    /*********************.       )))))))    
              .%%%%%%#      *%%%%%%,  *******/,     **********,      .))))))   
                .%%%%%%/      *%%%%%%,  **              ***


Geometry optimization cycle 1
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -0.563000   0.516000   0.007100    0.000000  0.000000  0.000000
   C   0.563000  -0.515900   0.007100    0.000000  0.000000  0.000000
   C  -1.929300  -0.150600  -0.007100    0.000000  0.000000  0.000000
   C   1.929400   0.150500  -0.007100   -0.000000  0.000000  0.000000
   H  -0.472400   1.166600  -0.870600    0.000000  0.000000  0.000000
   H  -0.482500   1.155100   0.894000    0.000000  0.000000  0.000000
   H   0.482500  -1.155100   0.894000    0.000000  0.000000  0.000000
   H   0.472300  -1.166500  -0.870600    0.000000  0.000000  0.000000
   H  -2.054200  -0.771000  -0.900300    0.000000  0.000000  0.000000
   H  -2.065100  -0.785600   0.874200    0.000000  0.000000  0.000000
   H  -2.720300   0.606000  -0.005800    0.000000  0.000000  0.000000
   H   2.054200   0.770900  -0.900300    0.000000  0.000000  0.000000
   H   2.720200  -0.606200  -0.0

Step    0 : Gradient = 7.159e-03/1.212e-02 (rms/max) Energy = -158.4574156378
Hessian Eigenvalues: 2.30000e-02 2.30000e-02 2.30000e-02 ... 3.42798e-01 3.42876e-01 3.42962e-01



Geometry optimization cycle 2
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -0.577546   0.505936   0.005194   -0.014546 -0.010064 -0.001906
   C   0.577541  -0.505956   0.005174    0.014541  0.009944 -0.001926
   C  -1.968081  -0.148162  -0.005943   -0.038781  0.002438  0.001157
   C   1.968109   0.148103  -0.005958    0.038709 -0.002397  0.001142
   H  -0.475363   1.165819  -0.875533   -0.002963 -0.000781 -0.004933
   H  -0.484745   1.155148   0.894773   -0.002245  0.000048  0.000773
   H   0.484718  -1.155207   0.894726    0.002218 -0.000107  0.000726
   H   0.475331  -1.165838  -0.875556    0.003031  0.000662 -0.004956
   H  -2.104256  -0.778115  -0.901143   -0.050056 -0.007115 -0.000843
   H  -2.112932  -0.791494   0.878394   -0.047832 -0.005894  0.004194
   H  -2.775190   0.603513  -0.004100   -0.054890 -0.002487  0.001700
   H   2.104268   0.778105  -0.901124    0.050068  0.007205 -0.000824
   H   2.775167  -0.603618  -0.0

Step    1 : Displace = 3.739e-02/5.505e-02 (rms/max) Trust = 1.000e-01 (=) Grad = 1.555e-03/2.940e-03 (rms/max) E (change) = -158.4586717417 (-1.256e-03) Quality = 0.845
Hessian Eigenvalues: 2.29856e-02 2.30000e-02 2.30000e-02 ... 3.42792e-01 3.42919e-01 3.64996e-01



Geometry optimization cycle 3
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -0.575293   0.506837   0.004420    0.002253  0.000902 -0.000773
   C   0.575290  -0.506880   0.004401   -0.002250 -0.000924 -0.000773
   C  -1.959944  -0.148316  -0.005433    0.008137 -0.000154  0.000510
   C   1.959953   0.148258  -0.005446   -0.008157  0.000156  0.000512
   H  -0.474237   1.169267  -0.875493    0.001126  0.003448  0.000039
   H  -0.482550   1.159683   0.892349    0.002194  0.004535 -0.002424
   H   0.482547  -1.159756   0.892307   -0.002171 -0.004549 -0.002419
   H   0.474221  -1.169296  -0.875524   -0.001111 -0.003458  0.000032
   H  -2.096761  -0.780059  -0.900040    0.007496 -0.001944  0.001102
   H  -2.103975  -0.792187   0.879369    0.008957 -0.000693  0.000975
   H  -2.764684   0.605079  -0.003466    0.010507  0.001567  0.000634
   H   2.096751   0.780054  -0.900018   -0.007516  0.001950  0.001106
   H   2.764674  -0.605157  -0.0

Step    2 : Displace = 7.308e-03/1.064e-02 (rms/max) Trust = 1.414e-01 (+) Grad = 6.095e-04/1.317e-03 (rms/max) E (change) = -158.4587495279 (-7.779e-05) Quality = 1.149
Hessian Eigenvalues: 2.27327e-02 2.30000e-02 2.30000e-02 ... 3.42792e-01 3.42919e-01 3.44880e-01



Geometry optimization cycle 4
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -0.575355   0.506160   0.003541   -0.000062 -0.000678 -0.000880
   C   0.575354  -0.506214   0.003521    0.000064  0.000665 -0.000880
   C  -1.958801  -0.147959  -0.004798    0.001143  0.000357  0.000634
   C   1.958801   0.147902  -0.004811   -0.001152 -0.000356  0.000635
   H  -0.474544   1.169532  -0.875750   -0.000307  0.000265 -0.000257
   H  -0.481577   1.161289   0.889752    0.000974  0.001606 -0.002597
   H   0.481585  -1.161371   0.889713   -0.000962 -0.001615 -0.002594
   H   0.474536  -1.169563  -0.875787    0.000315 -0.000268 -0.000263
   H  -2.096643  -0.780964  -0.898231    0.000118 -0.000905  0.001809
   H  -2.102382  -0.791664   0.880061    0.001593  0.000523  0.000692
   H  -2.763517   0.605066  -0.002790    0.001166 -0.000013  0.000676
   H   2.096624   0.780959  -0.898210   -0.000127  0.000905  0.001808
   H   2.763515  -0.605126  -0.0

Step    3 : Displace = 1.804e-03/3.208e-03 (rms/max) Trust = 2.000e-01 (+) Grad = 1.394e-04/3.139e-04 (rms/max) E (change) = -158.4587566866 (-7.159e-06) Quality = 1.217
Hessian Eigenvalues: 1.94885e-02 2.30000e-02 2.30004e-02 ... 3.42792e-01 3.42919e-01 3.60167e-01



Geometry optimization cycle 5
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -0.575524   0.505857   0.002746   -0.000169 -0.000303 -0.000794
   C   0.575524  -0.505915   0.002725    0.000170  0.000299 -0.000795
   C  -1.958946  -0.147858  -0.004185   -0.000145  0.000102  0.000614
   C   1.958945   0.147801  -0.004198    0.000144 -0.000101  0.000613
   H  -0.475073   1.169207  -0.876686   -0.000529 -0.000325 -0.000935
   H  -0.480915   1.162301   0.887979    0.000662  0.001012 -0.001772
   H   0.480924  -1.162386   0.887940   -0.000660 -0.001015 -0.001773
   H   0.475066  -1.169239  -0.876726    0.000530  0.000325 -0.000939
   H  -2.097636  -0.781755  -0.896856   -0.000993 -0.000791  0.001375
   H  -2.102184  -0.791071   0.881092    0.000198  0.000592  0.001031
   H  -2.763757   0.605017  -0.002232   -0.000240 -0.000050  0.000558
   H   2.097616   0.781748  -0.896837    0.000992  0.000789  0.001373
   H   2.763758  -0.605072  -0.0

Step    4 : Displace = 1.328e-03/2.148e-03 (rms/max) Trust = 2.828e-01 (+) Grad = 4.007e-05/6.599e-05 (rms/max) E (change) = -158.4587576715 (-9.849e-07) Quality = 1.317
Hessian Eigenvalues: 1.05197e-02 2.30000e-02 2.30039e-02 ... 3.42793e-01 3.42919e-01 3.54543e-01



Geometry optimization cycle 6
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -0.575589   0.505752   0.001886   -0.000065 -0.000105 -0.000860
   C   0.575589  -0.505811   0.001864    0.000065  0.000104 -0.000862
   C  -1.959094  -0.147807  -0.003502   -0.000148  0.000050  0.000683
   C   1.959094   0.147750  -0.003515    0.000149 -0.000050  0.000682
   H  -0.475744   1.168547  -0.878057   -0.000671 -0.000660 -0.001371
   H  -0.480272   1.163163   0.886348    0.000644  0.000862 -0.001631
   H   0.480281  -1.163250   0.886307   -0.000644 -0.000864 -0.001633
   H   0.475736  -1.168577  -0.878100    0.000670  0.000662 -0.001374
   H  -2.098488  -0.782539  -0.895471   -0.000853 -0.000784  0.001385
   H  -2.101797  -0.790249   0.882421    0.000388  0.000822  0.001328
   H  -2.763925   0.605053  -0.001678   -0.000168  0.000036  0.000553
   H   2.098470   0.782529  -0.895454    0.000854  0.000781  0.001382
   H   2.763927  -0.605108  -0.0

Step    5 : Displace = 1.415e-03/1.954e-03 (rms/max) Trust = 3.000e-01 (+) Grad = 6.764e-05/1.432e-04 (rms/max) E (change) = -158.4587581310 (-4.595e-07) Quality = 1.662
Hessian Eigenvalues: 3.77172e-03 2.30000e-02 2.30280e-02 ... 3.42792e-01 3.42920e-01 3.56741e-01



Geometry optimization cycle 7
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -0.575602   0.505716   0.000057   -0.000013 -0.000036 -0.001829
   C   0.575602  -0.505774   0.000032    0.000013  0.000037 -0.001832
   C  -1.959245  -0.147735  -0.002040   -0.000151  0.000072  0.001461
   C   1.959246   0.147678  -0.002055    0.000152 -0.000072  0.001461
   H  -0.477138   1.166956  -0.881222   -0.001395 -0.001591 -0.003165
   H  -0.478871   1.164850   0.883095    0.001401  0.001687 -0.003253
   H   0.478880  -1.164940   0.883048   -0.001401 -0.001691 -0.003259
   H   0.477130  -1.166981  -0.881271    0.001394  0.001596 -0.003171
   H  -2.099991  -0.784216  -0.892546   -0.001503 -0.001678  0.002925
   H  -2.100726  -0.788362   0.885381    0.001071  0.001887  0.002961
   H  -2.764024   0.605194  -0.000590   -0.000098  0.000141  0.001089
   H   2.099978   0.784200  -0.892534    0.001508  0.001671  0.002920
   H   2.764025  -0.605250  -0.0

Step    6 : Displace = 3.016e-03/3.920e-03 (rms/max) Trust = 3.000e-01 (=) Grad = 7.542e-05/1.758e-04 (rms/max) E (change) = -158.4587587364 (-6.053e-07) Quality = 1.356
Hessian Eigenvalues: 2.78535e-03 2.30000e-02 2.30837e-02 ... 3.42792e-01 3.42920e-01 3.64600e-01



Geometry optimization cycle 8
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -0.575534   0.505817  -0.000920    0.000067  0.000101 -0.000977
   C   0.575535  -0.505875  -0.000947   -0.000067 -0.000101 -0.000978
   C  -1.959212  -0.147685  -0.001256    0.000033  0.000051  0.000784
   C   1.959213   0.147628  -0.001271   -0.000032 -0.000051  0.000784
   H  -0.477845   1.166007  -0.883052   -0.000707 -0.000950 -0.001829
   H  -0.478088   1.165669   0.881486    0.000783  0.000819 -0.001609
   H   0.478097  -1.165761   0.881435   -0.000783 -0.000821 -0.001612
   H   0.477836  -1.166029  -0.883103    0.000706  0.000952 -0.001832
   H  -2.100577  -0.785156  -0.890958   -0.000585 -0.000940  0.001589
   H  -2.100017  -0.787214   0.887062    0.000709  0.001148  0.001681
   H  -2.763927   0.605324  -0.000123    0.000096  0.000130  0.000466
   H   2.100566   0.785136  -0.890947    0.000588  0.000936  0.001587
   H   2.763928  -0.605381  -0.0

Step    7 : Displace = 1.639e-03/2.217e-03 (rms/max) Trust = 3.000e-01 (=) Grad = 3.734e-05/8.867e-05 (rms/max) E (change) = -158.4587589198 (-1.834e-07) Quality = 1.167
Hessian Eigenvalues: 2.87970e-03 2.27405e-02 2.30000e-02 ... 3.42792e-01 3.42919e-01 3.56942e-01



Geometry optimization cycle 9
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -0.575480   0.505911  -0.001118    0.000055  0.000093 -0.000198
   C   0.575480  -0.505968  -0.001145   -0.000055 -0.000093 -0.000198
   C  -1.959143  -0.147646  -0.001094    0.000070  0.000039  0.000162
   C   1.959143   0.147588  -0.001109   -0.000070 -0.000039  0.000162
   H  -0.477945   1.165770  -0.883497   -0.000100 -0.000237 -0.000445
   H  -0.477890   1.165795   0.881230    0.000198  0.000126 -0.000256
   H   0.477899  -1.165888   0.881178   -0.000198 -0.000126 -0.000257
   H   0.477936  -1.165792  -0.883549    0.000100  0.000237 -0.000446
   H  -2.100557  -0.785417  -0.890576    0.000020 -0.000262  0.000381
   H  -2.099833  -0.786832   0.887488    0.000184  0.000382  0.000426
   H  -2.763828   0.605395  -0.000166    0.000099  0.000071 -0.000043
   H   2.100547   0.785397  -0.890566   -0.000019  0.000261  0.000381
   H   2.763828  -0.605452  -0.0

Step    8 : Displace = 3.870e-04/5.763e-04 (rms/max) Trust = 3.000e-01 (=) Grad = 7.814e-06/1.553e-05 (rms/max) E (change) = -158.4587589347 (-1.490e-08) Quality = 0.449
Hessian Eigenvalues: 2.87970e-03 2.27405e-02 2.30000e-02 ... 3.42792e-01 3.42919e-01 3.56942e-01
Converged! =D

    #==========================================================================#
    #| If this code has benefited your research, please support us by citing: |#
    #|                                                                        |#
    #| Wang, L.-P.; Song, C.C. (2016) "Geometry optimization made simple with |#
    #| translation and rotation coordinates", J. Chem, Phys. 144, 214108.     |#
    #| http://dx.doi.org/10.1063/1.4952956                                    |#
    #==========================================================================#
    Time elapsed since start of run_optimizer: 82.423 seconds


[[-1.087e+00  9.560e-01 -2.113e-03]
 [ 1.088e+00 -9.561e-01 -2.163e-03]
 [-3.702e+00 -2.790e-01 -2.068e-03]
 [ 3.702e+00  2.789e-01 -2.096e-03]
 [-9.032e-01  2.203e+00 -1.670e+00]
 [-9.031e-01  2.203e+00  1.665e+00]
 [ 9.031e-01 -2.203e+00  1.665e+00]
 [ 9.032e-01 -2.203e+00 -1.670e+00]
 [-3.969e+00 -1.484e+00 -1.683e+00]
 [-3.968e+00 -1.487e+00  1.677e+00]
 [-5.223e+00  1.144e+00 -3.137e-04]
 [ 3.969e+00  1.484e+00 -1.683e+00]
 [ 5.223e+00 -1.144e+00 -4.172e-04]
 [ 3.968e+00  1.487e+00  1.677e+00]]


In [12]:
import numpy as np
import copy

molecular_new = copy.deepcopy(molecular)
for i, atom in enumerate(molecular_new):
    atom[1] = mol_eq.atom_coords(unit="ANG")[i][0]
    atom[2] = mol_eq.atom_coords(unit="ANG")[i][1]
    atom[3] = mol_eq.atom_coords(unit="ANG")[i][2]
# molecular
%precision 3
molecular_new

[['C', -0.575, 0.506, -0.001],
 ['C', 0.575, -0.506, -0.001],
 ['C', -1.959, -0.148, -0.001],
 ['C', 1.959, 0.148, -0.001],
 ['H', -0.478, 1.166, -0.883],
 ['H', -0.478, 1.166, 0.881],
 ['H', 0.478, -1.166, 0.881],
 ['H', 0.478, -1.166, -0.884],
 ['H', -2.101, -0.785, -0.891],
 ['H', -2.100, -0.787, 0.887],
 ['H', -2.764, 0.605, -0.000],
 ['H', 2.101, 0.785, -0.891],
 ['H', 2.764, -0.605, -0.000],
 ['H', 2.100, 0.787, 0.887]]