In [5]:
from pyscf.geomopt.geometric_solver import optimize
from pyscf import gto, scf

MOL = """   
   -1.0551   -0.6580    0.2446 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9716    0.7805   -0.2349 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.2952   -1.2327   -0.1536 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.4469    1.1915    0.1309 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2846   -0.0814    0.0130 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.1742   -0.6896    1.3340 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.8887   -1.2020   -0.2082 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.1092    0.8265   -1.3217 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7240    1.4220    0.2327 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.5683   -2.1041    0.4489 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.2713   -1.5481   -1.2036 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.8210    1.9934   -0.5127 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.4759    1.5560    1.1648 H   0  0  0  0  0  0  0  0  0  0  0  0
    1.8979   -0.2164    0.9106 H   0  0  0  0  0  0  0  0  0  0  0  0
    1.9655   -0.0323   -0.8435 H   0  0  0  0  0  0  0  0  0  0  0  0
"""
molecular = []
for line in MOL.split("\n"):
    line_split = line.split()
    atom = []
    if len(line_split):
        atom.append(line_split[3])
        atom.append(float(line_split[0]))
        atom.append(float(line_split[1]))
        atom.append(float(line_split[2]))
        molecular.append(atom)
print(molecular)

mol = gto.M(atom=molecular, basis="ccpvdz")
mdft = mol.KS()
mdft.xc = "b3lyp"
mdft.kernel()
mol_eq = optimize(mdft, maxsteps=100)
print(mol_eq.atom_coords())

[['C', -1.0551, -0.658, 0.2446], ['C', -0.9716, 0.7805, -0.2349], ['C', 0.2952, -1.2327, -0.1536], ['C', 0.4469, 1.1915, 0.1309], ['C', 1.2846, -0.0814, 0.013], ['H', -1.1742, -0.6896, 1.334], ['H', -1.8887, -1.202, -0.2082], ['H', -1.1092, 0.8265, -1.3217], ['H', -1.724, 1.422, 0.2327], ['H', 0.5683, -2.1041, 0.4489], ['H', 0.2713, -1.5481, -1.2036], ['H', 0.821, 1.9934, -0.5127], ['H', 0.4759, 1.556, 1.1648], ['H', 1.8979, -0.2164, 0.9106], ['H', 1.9655, -0.0323, -0.8435]]
converged SCF energy = -196.559179076035


geometric-optimize called with the following command line:
/home/dhem/anaconda3/envs/pyscf/lib/python3.11/site-packages/ipykernel_launcher.py --f=/home/dhem/.local/share/jupyter/runtime/kernel-v2-22230h6Ov2MosMLMk.json

                                        ())))))))))))))))/                     
                                    ())))))))))))))))))))))))),                
                                *)))))))))))))))))))))))))))))))))             
                        #,    ()))))))))/                .)))))))))),          
                      #%%%%,  ())))))                        .))))))))*        
                      *%%%%%%,  ))              ..              ,))))))).      
                        *%%%%%%,         ***************/.        .)))))))     
                #%%/      (%%%%%%,    /*********************.       )))))))    
              .%%%%%%#      *%%%%%%,  *******/,     **********,      .))))))   
                .%%%%%%/      *%%%%%%,  **              ****


Geometry optimization cycle 1
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -1.055100  -0.658000   0.244600    0.000000  0.000000  0.000000
   C  -0.971600   0.780500  -0.234900    0.000000  0.000000  0.000000
   C   0.295200  -1.232700  -0.153600    0.000000  0.000000  0.000000
   C   0.446900   1.191500   0.130900    0.000000  0.000000  0.000000
   C   1.284600  -0.081400   0.013000    0.000000  0.000000  0.000000
   H  -1.174200  -0.689600   1.334000    0.000000  0.000000  0.000000
   H  -1.888700  -1.202000  -0.208200    0.000000  0.000000  0.000000
   H  -1.109200   0.826500  -1.321700    0.000000  0.000000  0.000000
   H  -1.724000   1.422000   0.232700    0.000000  0.000000  0.000000
   H   0.568300  -2.104100   0.448900    0.000000  0.000000  0.000000
   H   0.271300  -1.548100  -1.203600    0.000000  0.000000  0.000000
   H   0.821000   1.993400  -0.512700   -0.000000  0.000000  0.000000
   H   0.475900   1.556000   1.1

Step    0 : Gradient = 6.878e-03/1.186e-02 (rms/max) Energy = -196.5591790760
Hessian Eigenvalues: 2.32323e-02 2.46365e-02 3.80742e-02 ... 3.43497e-01 3.43834e-01 3.44055e-01



Geometry optimization cycle 2
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -1.070317  -0.668139   0.242322   -0.015217 -0.010139 -0.002278
   C  -0.985739   0.792581  -0.233102   -0.014139  0.012081  0.001798
   C   0.299980  -1.254252  -0.155721    0.004780 -0.021552 -0.002121
   C   0.454482   1.213088   0.133436    0.007582  0.021588  0.002536
   C   1.311645  -0.083435   0.013471    0.027045 -0.002035  0.000471
   H  -1.194310  -0.695758   1.339790   -0.020110 -0.006158  0.005790
   H  -1.916123  -1.219527  -0.199822   -0.027423 -0.017527  0.008378
   H  -1.130417   0.833678  -1.327475   -0.021217  0.007178 -0.005775
   H  -1.749386   1.442514   0.224258   -0.025386  0.020514 -0.008442
   H   0.572105  -2.139714   0.440537    0.003805 -0.035614 -0.008363
   H   0.265691  -1.578371  -1.210061   -0.005609 -0.030271 -0.006461
   H   0.828779   2.028928  -0.505115    0.007779  0.035528  0.007585
   H   0.475477   1.588454   1.1

Step    1 : Displace = 3.012e-02/3.936e-02 (rms/max) Trust = 1.000e-01 (=) Grad = 8.629e-04/1.636e-03 (rms/max) E (change) = -196.5613359293 (-2.157e-03) Quality = 0.911
Hessian Eigenvalues: 2.32323e-02 2.45003e-02 3.80755e-02 ... 3.43597e-01 3.43951e-01 3.46781e-01



Geometry optimization cycle 3
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -1.068826  -0.667036   0.243788    0.001491  0.001102  0.001467
   C  -0.984347   0.790948  -0.234288    0.001392 -0.001634 -0.001186
   C   0.298980  -1.252404  -0.156398   -0.000999  0.001848 -0.000677
   C   0.453413   1.211112   0.134058   -0.001069 -0.001975  0.000621
   C   1.309499  -0.083475   0.013520   -0.002145 -0.000041  0.000049
   H  -1.190608  -0.693586   1.341839    0.003702  0.002173  0.002049
   H  -1.915667  -1.219350  -0.194033    0.000455  0.000176  0.005789
   H  -1.126895   0.830775  -1.329253    0.003522 -0.002903 -0.001778
   H  -1.748788   1.441988   0.219047    0.000598 -0.000526 -0.005211
   H   0.571995  -2.138515   0.437874   -0.000110  0.001199 -0.002664
   H   0.265027  -1.574079  -1.211465   -0.000664  0.004292 -0.001404
   H   0.828771   2.027148  -0.503097   -0.000008 -0.001780  0.002018
   H   0.474470   1.584320   1.1

Step    2 : Displace = 3.752e-03/5.709e-03 (rms/max) Trust = 1.414e-01 (+) Grad = 3.299e-04/6.758e-04 (rms/max) E (change) = -196.5613647861 (-2.886e-05) Quality = 1.369
Hessian Eigenvalues: 1.42821e-02 2.32323e-02 3.80632e-02 ... 3.43550e-01 3.43953e-01 3.69307e-01



Geometry optimization cycle 4
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -1.067603  -0.666123   0.245724    0.001224  0.000914  0.001936
   C  -0.983337   0.789454  -0.235835    0.001010 -0.001494 -0.001547
   C   0.297883  -1.251515  -0.157633   -0.001097  0.000889 -0.001235
   C   0.452369   1.209848   0.135238   -0.001044 -0.001264  0.001180
   C   1.308298  -0.083810   0.013620   -0.001202 -0.000335  0.000100
   H  -1.185121  -0.689887   1.344551    0.005487  0.003698  0.002712
   H  -1.916855  -1.219965  -0.185131   -0.001188 -0.000615  0.008902
   H  -1.122254   0.826028  -1.331601    0.004640 -0.004747 -0.002347
   H  -1.749830   1.442367   0.211009   -0.001042  0.000379 -0.008038
   H   0.571735  -2.139658   0.432994   -0.000260 -0.001143 -0.004879
   H   0.262576  -1.569739  -1.213739   -0.002451  0.004340 -0.002274
   H   0.828843   2.027374  -0.499137    0.000072  0.000225  0.003960
   H   0.471941   1.580359   1.1

Step    3 : Displace = 4.987e-03/8.758e-03 (rms/max) Trust = 2.000e-01 (+) Grad = 2.588e-04/3.881e-04 (rms/max) E (change) = -196.5613806218 (-1.584e-05) Quality = 1.459
Hessian Eigenvalues: 5.92181e-03 2.32323e-02 3.81279e-02 ... 3.43609e-01 3.43957e-01 4.68398e-01



Geometry optimization cycle 5
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -1.066783  -0.665382   0.248495    0.000820  0.000741  0.002771
   C  -0.982707   0.787894  -0.238031    0.000630 -0.001559 -0.002195
   C   0.296528  -1.251255  -0.159391   -0.001355  0.000260 -0.001758
   C   0.451289   1.208925   0.136878   -0.001079 -0.000923  0.001640
   C   1.307641  -0.084426   0.013725   -0.000657 -0.000615  0.000105
   H  -1.177650  -0.684601   1.348309    0.007471  0.005286  0.003758
   H  -1.919346  -1.220989  -0.173523   -0.002490 -0.001023  0.011607
   H  -1.116186   0.819221  -1.334823    0.006069 -0.006807 -0.003223
   H  -1.752044   1.443034   0.200632   -0.002214  0.000667 -0.010376
   H   0.571175  -2.142455   0.426207   -0.000560 -0.002797 -0.006787
   H   0.258505  -1.564616  -1.216932   -0.004071  0.005123 -0.003193
   H   0.828993   2.028960  -0.493477    0.000150  0.001586  0.005660
   H   0.468120   1.575712   1.1

Step    4 : Displace = 6.645e-03/1.150e-02 (rms/max) Trust = 2.828e-01 (+) Grad = 3.587e-04/7.410e-04 (rms/max) E (change) = -196.5613925994 (-1.198e-05) Quality = 1.353
Hessian Eigenvalues: 4.00724e-03 2.32323e-02 3.81675e-02 ... 3.43671e-01 3.43970e-01 4.38787e-01



Geometry optimization cycle 6
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -1.066766  -0.665220   0.250486    0.000016  0.000163  0.001991
   C  -0.982768   0.787144  -0.239547   -0.000061 -0.000750 -0.001517
   C   0.295666  -1.251665  -0.160529   -0.000862 -0.000409 -0.001139
   C   0.450734   1.208616   0.137914   -0.000555 -0.000309  0.001035
   C   1.307562  -0.085022   0.013754   -0.000079 -0.000596  0.000029
   H  -1.172661  -0.680907   1.350852    0.004990  0.003694  0.002542
   H  -1.921263  -1.221694  -0.166617   -0.001918 -0.000706  0.006906
   H  -1.112337   0.814450  -1.336923    0.003848 -0.004771 -0.002100
   H  -1.753708   1.443504   0.194619   -0.001664  0.000470 -0.006013
   H   0.570672  -2.144918   0.421845   -0.000503 -0.002463 -0.004362
   H   0.255308  -1.561580  -1.219035   -0.003197  0.003036 -0.002103
   H   0.829067   2.030485  -0.489738    0.000074  0.001525  0.003739
   H   0.465326   1.572763   1.1

Step    5 : Displace = 4.268e-03/6.870e-03 (rms/max) Trust = 3.000e-01 (+) Grad = 2.246e-04/5.199e-04 (rms/max) E (change) = -196.5613973359 (-4.736e-06) Quality = 1.236
Hessian Eigenvalues: 4.00422e-03 2.32323e-02 3.78626e-02 ... 3.43561e-01 3.43952e-01 3.69492e-01



Geometry optimization cycle 7
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -1.067117  -0.665401   0.251185   -0.000351 -0.000181  0.000699
   C  -0.983050   0.787013  -0.239978   -0.000282 -0.000131 -0.000431
   C   0.295349  -1.252088  -0.160781   -0.000317 -0.000424 -0.000251
   C   0.450663   1.208521   0.138130   -0.000072 -0.000095  0.000217
   C   1.307621  -0.085389   0.013719    0.000058 -0.000367 -0.000035
   H  -1.171423  -0.679851   1.351633    0.001238  0.001055  0.000782
   H  -1.921890  -1.221908  -0.165346   -0.000627 -0.000213  0.001271
   H  -1.111503   0.812937  -1.337443    0.000834 -0.001513 -0.000520
   H  -1.754104   1.443567   0.193728   -0.000396  0.000063 -0.000891
   H   0.570377  -2.145873   0.420810   -0.000295 -0.000955 -0.001035
   H   0.254027  -1.560898  -1.219566   -0.001281  0.000682 -0.000530
   H   0.829104   2.030933  -0.488786    0.000037  0.000448  0.000952
   H   0.464456   1.571791   1.1

Step    6 : Displace = 1.079e-03/1.937e-03 (rms/max) Trust = 3.000e-01 (=) Grad = 6.472e-05/1.614e-04 (rms/max) E (change) = -196.5613982716 (-9.358e-07) Quality = 1.089
Hessian Eigenvalues: 4.32421e-03 2.32321e-02 3.43975e-02 ... 3.43532e-01 3.43947e-01 3.75913e-01



Geometry optimization cycle 8
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -1.067343  -0.665553   0.251334   -0.000226 -0.000153  0.000149
   C  -0.983198   0.786975  -0.239954   -0.000148 -0.000038  0.000024
   C   0.295196  -1.252308  -0.160728   -0.000153 -0.000220  0.000053
   C   0.450677   1.208354   0.138094    0.000014 -0.000167 -0.000036
   C   1.307558  -0.085635   0.013682   -0.000062 -0.000246 -0.000038
   H  -1.171587  -0.679884   1.351747   -0.000164 -0.000033  0.000114
   H  -1.921961  -1.221937  -0.165642   -0.000071 -0.000029 -0.000296
   H  -1.111721   0.812776  -1.337375   -0.000218 -0.000161  0.000068
   H  -1.753994   1.443507   0.194218    0.000110 -0.000061  0.000490
   H   0.570199  -2.146098   0.420866   -0.000179 -0.000225  0.000056
   H   0.253660  -1.560991  -1.219534   -0.000367 -0.000094  0.000032
   H   0.829118   2.030783  -0.488801    0.000014 -0.000150 -0.000015
   H   0.464402   1.571505   1.1

Step    7 : Displace = 1.780e-04/4.064e-04 (rms/max) Trust = 3.000e-01 (=) Grad = 1.308e-05/2.460e-05 (rms/max) E (change) = -196.5613983562 (-8.456e-08) Quality = 0.921
Hessian Eigenvalues: 4.32421e-03 2.32321e-02 3.43975e-02 ... 3.43532e-01 3.43947e-01 3.75913e-01
Converged! =D

    #==========================================================================#
    #| If this code has benefited your research, please support us by citing: |#
    #|                                                                        |#
    #| Wang, L.-P.; Song, C.C. (2016) "Geometry optimization made simple with |#
    #| translation and rotation coordinates", J. Chem, Phys. 144, 214108.     |#
    #| http://dx.doi.org/10.1063/1.4952956                                    |#
    #==========================================================================#
    Time elapsed since start of run_optimizer: 108.727 seconds


[[-2.017 -1.258  0.475]
 [-1.858  1.487 -0.453]
 [ 0.558 -2.367 -0.304]
 [ 0.852  2.283  0.261]
 [ 2.471 -0.162  0.026]
 [-2.214 -1.285  2.554]
 [-3.632 -2.309 -0.313]
 [-2.101  1.536 -2.527]
 [-3.315  2.728  0.367]
 [ 1.078 -4.056  0.795]
 [ 0.479 -2.95  -2.305]
 [ 1.567  3.838 -0.924]
 [ 0.878  2.97   2.229]
 [ 3.648 -0.431  1.722]
 [ 3.78  -0.064 -1.589]]


In [6]:
import numpy as np
import copy

molecular_new = copy.deepcopy(molecular)
for i, atom in enumerate(molecular_new):
    atom[1] = mol_eq.atom_coords(unit="ANG")[i][0]
    atom[2] = mol_eq.atom_coords(unit="ANG")[i][1]
    atom[3] = mol_eq.atom_coords(unit="ANG")[i][2]
# molecular
%precision 3
molecular_new

[['C', -1.067, -0.666, 0.251],
 ['C', -0.983, 0.787, -0.240],
 ['C', 0.295, -1.252, -0.161],
 ['C', 0.451, 1.208, 0.138],
 ['C', 1.308, -0.086, 0.014],
 ['H', -1.172, -0.680, 1.352],
 ['H', -1.922, -1.222, -0.166],
 ['H', -1.112, 0.813, -1.337],
 ['H', -1.754, 1.444, 0.194],
 ['H', 0.570, -2.146, 0.421],
 ['H', 0.254, -1.561, -1.220],
 ['H', 0.829, 2.031, -0.489],
 ['H', 0.464, 1.572, 1.180],
 ['H', 1.930, -0.228, 0.911],
 ['H', 2.000, -0.034, -0.841]]